project:
  type: book

book:
  title: "GitHub Pages Starter Guide"
  author: "IQSS"
  date: "last-modified"
  page-navigation: true
  search: true
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - create.qmd
    - part: "Customization"
      chapters:
        - template.qmd
        - customizing.qmd
        - domain.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple

execute:
  freeze: auto

