project:
  type: book

book:
  title: "Professional Website Starter Guide"
  author: "IQSS"
  date: "last-modified"
  page-navigation: true
  search: true
  sidebar:
    search: true
    collapse-level: 1
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - part: "Google Sites"
      chapters:
        - GS_start.qmd
        - GS_create.qmd
        - GS_customize.qmd
        - GS_domain.qmd
    - part: "Online GitHub Editor"
      chapters:
        - OGHE_start.qmd
        - OGHE_create.qmd
        - OGHE_template.qmd
        - OGHE_customize.qmd
        - domain.qmd
    - part: "GitHub Desktop"
      chapters:
        - GHD_start.qmd
        - GHD_create.qmd
        - GHD_template.qmd
        - GHD_customize.qmd
        - domain.qmd
    - part: "RStudio and Git"
      chapters:
        - RSG_start.qmd
        - RSG_create.qmd
        - RSG_template.qmd
        - RSG_customize.qmd
        - domain.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple
    number-sections: false
    css: styles.css

execute:
  freeze: auto

