# Customize Your Website {.sec-google}

You are now ready to customize the template with your information. Google Sites is driven by its user interface. There is no coding that you need to do. Instead, there are pop-ups, and various tool menus that allow you to edit your site, insert or remove content, create or delete pages, and edit the theme.

Using the "Graduates" template as an example, you can start with three pages: (1) About, (2) Resume, and (3) Research & Projects.

You can change these page names by navigating on the right-most menu bar to the "Pages" tab, and then double-clicking on the page name to change it. You can also use the "+" button at the bottom of the menu bar to add pages. You can use the three-dot menu next to each page name to delete or duplicate a page.

For example, you may wish to change "About" to "Home".

<hr>

## About Page

1. Add your name to the header by simply clicking on the "Tina Smith, PhD" and putting your name there instead.
2. Introduce yourself by editing the first text box. 
  <ol type="a">
    <li>Hover over the text box, and click on the pencil icon to edit.</li>
    <li>You can change the text type (e.g., title), font, size, styles, and formatting in the tool menu that pops up above the text box.</li>
  </ol>
3. You can add an image of yourself.
  <ol type="a">
    <li>Click on the existing image.</li>
    <li>In the tool bar that pops up, select the three dots.</li>
    <li>Hover over "Replace image" and then click "Upload".</li>
    <li>From your computer, select the image you would like to add.</li>
  </ol>
4. You can choose to move, add, or delete sections on your homepage if you wish.
  <ol type="a">
    <li>To move a section, you can hover over the content, move your cursor to the left-most part of the content (where there are 10 dots in 2 columns), and drag the section to your desired location.</li>
    <li>To add a section, make sure the menu bar on the right side is on the "Insert" tab, and select your desired content block.</li>
    <li>To delete a section, hover over it, and in the left-most pop-up menu, click the trash icon.</li>
  </ol>

<hr>

## Resume Page

1. Navigate to the Resume Page by clicking on "Resume" in the top header.
2. Google Slides allows the option to include resume sections as plain text on the site, or as a Google Doc/PDF, or both. Choose whichever you'd like.
3. You can simply click the plain text sections if you'd like to include those. If not, hover over each and select the trash icon in the left-side pop-up menu to delete them.

<details>
<summary>If you have your resume as a Google Doc:</summary>
  <ol type="a">
    <li>In the right-side menu bar under the "Insert" tab, select "Docs".</li>
    <li>In the pop-up menu, select your Google Docs resume.</li>
    <li>Click the blue "Insert" button.</li>
    <li>Note that this will insert the Google Doc in a new section under your current section.</li>
  </ol>
</details>
<details>
<summary>If you have your resume as a PDF:</summary>
  <ol type="a">
    <li>You need to upload your PDF file to your Google Drive.</li>
    <li>In the right-side menu bar under the "Insert" tab, select "Drive".</li>
    <li>In the pop-up menu, navigate to and select your PDF resume.</li>
    <li>Click the blue "Insert" button.</li>
    <li>Not that this will insert the PDF in a new section under your current section.</li>
  </ol>
</details>

If you get any messages about permissions for files:

1. Make sure that the drop-down is set to "Viewer" and then click "Share".
2. Navigate to the Google Drive that has your file.
3. Access the file.
4. Click the blue "Share" button at the top-right.
5. Under "General Access", change the drop-down to "Anyone with the link" and make sure that the second drop-down says "Viewer".
6. Click the blue "Done" button.
7. Navigate back to your Google Sites webpage.

<hr>

## Research & Projects Page

You can edit the text boxes here as you normally would to add content about projects that you'd like to highlight.

You can also add or remove sections as you see fit, also as described earlier.

<hr>

## Publishing Your Site

Once you are done editing your site and you are ready to publish it.

Tip: In the top menu bar, there is an icon that looks like a computer and a phone. When you hover over it, it says "Preview". You can use this button to preview what your site will look like on different screens (mobile, tablet, computer). You can click the blue "X" to exit back to the editor.

1. Click the purple Publish button in the top right corner.
2. Put a name for your URL in the "Web address" box. Just below the box will show you what your URL will look like: "https://sites.google.com/", etc.
3. Under the "Who can view my site" make sure to click the blue "MANAGE" button.
4. In the pop-up, at the "Published Site" section, change the drop-down to "Public".
5. Click "Done".
6. Now, click the purple "Publish" button at the bottom of the pop-up.
7. Congrats, you should be done!

<details>
<summary>If you get an error about access to a file, you need to make sure the file is publicly viewable:</sumamry>
  <ol type="a">
    <li>Go to your Google Drive account where the file is stored.</li>
    <li>Access the file.</li>
    <li>Click the blue "Share" button at the top-right.</li>
    <li>Under "General Access", change the drop-down to "Anyone with the link" and make sure that the second drop-down says "Viewer".</li>
    <li>Click the blue "Done" button.</li>
    <li>Navigate back to your Google Sites webpage.</li>
    <li>Re-publish your site.</li>
  </ol>
</details>




