# Introduction {.unnumbered}

## The site is currently under maintenance. Please return shortly.

The following is a quick starter guide designed to get you acquainted with GitHub Pages, an option for you to create a personal website. If you'd rather start with a website on Google Sites (no coding necessary!), we include those instructions first.

We include instructions for editing your website with four options. For the option you would like to choose, simply click on its link below for detailed instructions to get started.

1. [Google Sites](GS_start.html)
2. [The online file editor through GitHub](OGHE_start.html)
3. [RStudio and Git](RSG_start.html)

Feel free to choose the option that best fits your technical comfort level. If you are already used to R/RStudio/Git, the last option may be best for you. If you don't know what those are, but you know how to code in HTML, feel free to use option 2. If you have no clue how to code (that's OK!), then a Google Sites page might be right for you.

Additionally, we include instructions for finding and using templates, customizing your site, and connecting your site to a custom domain.

Note: In Google Sites, support for custom domains is currently not available for managed accounts, like a g.harvard.edu account. If you really want to use a custom domain (i.e. yourname.com), then you should either use GitHub Pages or use a personal Google account to make your Google Site.
